name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run lint
        npm run dist
    - uses: actions/upload-artifact@v4
      with:
        name: linux-binaries
        path: |
          dist/ffmuc-meet-amd64.deb
          dist/ffmuc-meet-x86_64.AppImage
          dist/ffmuc-meet-arm64.deb
          dist/ffmuc-meet-arm64.AppImage
          dist/latest-linux.yml
          dist/latest-linux-arm64.yml
  build-mac:
    name: macOS
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Prepare for app signing and notarization
      env:
        API_KEY: ${{ secrets.api_key }}
      if: ${{ env.API_KEY }}
      run: |
        mkdir -p ~/private_keys/
        echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
        echo "CSC_LINK=${{ secrets.mac_certs }}" >> $GITHUB_ENV
        echo "CSC_KEY_PASSWORD=${{ secrets.mac_certs_password }}" >> $GITHUB_ENV
        echo "CSC_FOR_PULL_REQUEST=true" >> $GITHUB_ENV
        echo "API_KEY_FILE=~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8" >> $GITHUB_ENV
        echo "API_KEY_ID=${{ secrets.api_key_id }}" >> $GITHUB_ENV
        echo "API_KEY_ISSUER_ID=${{ secrets.api_key_issuer_id }}" >> $GITHUB_ENV
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run dist
    - uses: actions/upload-artifact@v4
      with:
        name: mac-binaries
        path: |
          dist/ffmuc-meet.dmg
          dist/ffmuc-meet.zip
          dist/latest-mac.yml
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run dist
    - uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: |
          dist/ffmuc-meet.exe
          dist/latest.yml

  winget-release:
    name: Publish to WinGet
    runs-on: ubuntu-latest
    needs: build-windows
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/checkout@v4
    - name: Publish WinGet Manifest
      uses: vedantmgoyal9/winget-releaser@v2
      with:
        identifier: freifunkMUC.FreifunkMeet
        installers-regex: '\.exe$' # Only .exe files
        max-versions-to-keep: 5 # keep only latest 5 versions
        token: ${{ secrets.GITHUB_TOKEN }}