name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get Github App Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ vars.FFMUC_BOT_CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            jitsi-meet-electron
            winget-pkgs

      - uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: freifunkMUC.FreifunkMeet
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ steps.app-token.outputs.token }}
